server:
  port: 7000
spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/scw?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #开启监控过滤器
    filters: stat
  redis:
    host: 192.168.76.200
    port: 6379
application:
  name: SCW-USER
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/offcn/user/mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: true
  instance:
    appname: SCW-USER
    prefer-ip-address: true
logging:
  file:
    path: D:\log\dlogscw-user.log
  level:
    com:
      offcn: debug
sms:
  host: http://dingxin.market.alicloudapi.com
  path: /dx/sendSms
  method: POST
  appcode: a243170b7746401ca8303cc1d64b902e